package com.skylens.presentation.ui.screens.onboarding

import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.pager.HorizontalPager
import androidx.compose.foundation.pager.rememberPagerState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.launch

data class OnboardingPage(
    val emoji: String,
    val title: String,
    val description: String
)

@OptIn(ExperimentalFoundationApi::class)
@Composable
fun OnboardingScreen(
    onComplete: () -> Unit
) {
    val context = androidx.compose.ui.platform.LocalContext.current

    // Mark onboarding as seen when completed
    val markOnboardingComplete = {
        val sharedPrefs = context.getSharedPreferences("skylens_prefs", android.content.Context.MODE_PRIVATE)
        sharedPrefs.edit().putBoolean("has_seen_onboarding", true).apply()
        onComplete()
    }

    val pages = listOf(
        OnboardingPage(
            emoji = "✈️",
            title = "Welcome to SkyLens",
            description = "Discover landmarks and learn about the world below as you fly. Get real-time information about what you're seeing from your airplane window."
        ),
        OnboardingPage(
            emoji = "🗺️",
            title = "Live Flight Tracking",
            description = "Your GPS position is tracked in real-time. See your flight path on the map and watch as landmarks come into view."
        ),
        OnboardingPage(
            emoji = "🏔️",
            title = "Smart Landmark Detection",
            description = "Mountains, cities, rivers, monuments - we identify them all based on your altitude and position. Get notifications when landmarks become visible."
        ),
        OnboardingPage(
            emoji = "🤖",
            title = "AI-Powered Stories",
            description = "Each landmark comes with fascinating facts and stories generated by AI. Learn the history, significance, and interesting details about what you see."
        ),
        OnboardingPage(
            emoji = "📴",
            title = "Works Offline",
            description = "Download offline packs before your flight. All landmarks, maps, and stories work without internet - perfect for airplane mode."
        ),
        OnboardingPage(
            emoji = "🚀",
            title = "Ready to Fly?",
            description = "Enter your departure and arrival airports to get started. Download your flight pack and you're ready for an amazing journey!"
        )
    )

    val pagerState = rememberPagerState(pageCount = { pages.size })
    val scope = rememberCoroutineScope()

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(MaterialTheme.colorScheme.background)
    ) {
        Column(
            modifier = Modifier.fillMaxSize()
        ) {
            // Pager
            HorizontalPager(
                state = pagerState,
                modifier = Modifier.weight(1f)
            ) { page ->
                OnboardingPageContent(pages[page])
            }

            // Page Indicators
            Row(
                Modifier
                    .fillMaxWidth()
                    .padding(bottom = 16.dp),
                horizontalArrangement = Arrangement.Center
            ) {
                repeat(pages.size) { iteration ->
                    val color = if (pagerState.currentPage == iteration) {
                        MaterialTheme.colorScheme.primary
                    } else {
                        MaterialTheme.colorScheme.onSurface.copy(alpha = 0.3f)
                    }
                    Box(
                        modifier = Modifier
                            .padding(4.dp)
                            .clip(CircleShape)
                            .background(color)
                            .size(8.dp)
                    )
                }
            }

            // Navigation Buttons
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 16.dp, vertical = 24.dp),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                // Skip button (only show if not on last page)
                if (pagerState.currentPage < pages.size - 1) {
                    TextButton(onClick = markOnboardingComplete) {
                        Text("Skip")
                    }
                } else {
                    Spacer(modifier = Modifier.width(1.dp))
                }

                // Next/Get Started button
                Button(
                    onClick = {
                        if (pagerState.currentPage < pages.size - 1) {
                            scope.launch {
                                pagerState.animateScrollToPage(pagerState.currentPage + 1)
                            }
                        } else {
                            markOnboardingComplete()
                        }
                    },
                    modifier = Modifier.height(56.dp)
                ) {
                    Text(
                        text = if (pagerState.currentPage < pages.size - 1) "Next" else "Get Started",
                        modifier = Modifier.padding(horizontal = 16.dp)
                    )
                }
            }
        }
    }
}

@Composable
private fun OnboardingPageContent(page: OnboardingPage) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Text(
            text = page.emoji,
            style = MaterialTheme.typography.displayLarge,
            modifier = Modifier.size(120.dp)
        )

        Spacer(modifier = Modifier.height(48.dp))

        Text(
            text = page.title,
            style = MaterialTheme.typography.headlineLarge,
            fontWeight = FontWeight.Bold,
            textAlign = TextAlign.Center
        )

        Spacer(modifier = Modifier.height(24.dp))

        Text(
            text = page.description,
            style = MaterialTheme.typography.bodyLarge,
            textAlign = TextAlign.Center,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            lineHeight = MaterialTheme.typography.bodyLarge.lineHeight.times(1.5f),
            modifier = Modifier.padding(horizontal = 16.dp)
        )
    }
}
