#!/bin/bash
# Quick Setup Guide for SkyLens
# This script provides copy-paste commands for macOS setup

echo "🛫 SkyLens Quick Setup Commands"
echo "================================="
echo ""
echo "Follow these steps to set up your development environment:"
echo ""

echo "📦 Step 1: Install Java 17"
echo "----------------------------"
echo "# Using Homebrew (recommended):"
echo "brew install openjdk@17"
echo ""
echo "# Link it:"
echo "sudo ln -sfn /opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-17.jdk"
echo ""
echo "# Add to ~/.zshrc:"
echo 'echo '\''export PATH="/opt/homebrew/opt/openjdk@17/bin:\$PATH"'\'' >> ~/.zshrc'
echo 'echo '\''export JAVA_HOME=\$(/usr/libexec/java_home -v 17)'\'' >> ~/.zshrc'
echo "source ~/.zshrc"
echo ""

echo "🏗 Step 2: Install Android Studio"
echo "-----------------------------------"
echo "# Download and install from:"
echo "open https://developer.android.com/studio"
echo ""
echo "# After installation, add to ~/.zshrc:"
echo 'echo '\''export ANDROID_HOME=\$HOME/Library/Android/sdk'\'' >> ~/.zshrc'
echo 'echo '\''export PATH=\$PATH:\$ANDROID_HOME/emulator'\'' >> ~/.zshrc'
echo 'echo '\''export PATH=\$PATH:\$ANDROID_HOME/platform-tools'\'' >> ~/.zshrc'
echo "source ~/.zshrc"
echo ""

echo "🔑 Step 3: Create Configuration File"
echo "--------------------------------------"
echo "cd /Users/I808883/app/claude"
echo "cp android/local.properties.example android/local.properties"
echo ""
echo "# Then edit android/local.properties with your API keys"
echo "# See docs/API_INTEGRATION.md for detailed instructions"
echo ""

echo "☁️ Step 4: Set Up Supabase"
echo "----------------------------"
echo "# 1. Create project at https://supabase.com"
echo "open https://supabase.com/dashboard"
echo ""
echo "# 2. Run SQL migrations:"
echo "# Go to Supabase Dashboard → SQL Editor"
echo "# Copy and execute each file in order:"
echo "#   - docs/migrations/001_create_users.sql"
echo "#   - docs/migrations/002_create_airports.sql"
echo "#   - docs/migrations/003_create_landmarks.sql"
echo "#   - docs/migrations/004_create_trips.sql"
echo ""
echo "# 3. Get credentials from Settings → API"
echo "# Add to android/local.properties:"
echo "#   SUPABASE_URL=https://xxxxx.supabase.co"
echo "#   SUPABASE_ANON_KEY=eyJhbG..."
echo ""

echo "🔐 Step 5: Set Up Google OAuth"
echo "--------------------------------"
echo "# 1. Create project at Google Cloud Console"
echo "open https://console.cloud.google.com"
echo ""
echo "# 2. Enable Google+ API"
echo "# 3. Configure OAuth consent screen"
echo "# 4. Create OAuth 2.0 Client ID (Web application type)"
echo "# 5. Add Web Client ID to android/local.properties:"
echo "#   GOOGLE_WEB_CLIENT_ID=123-abc.apps.googleusercontent.com"
echo ""
echo "# See docs/API_INTEGRATION.md for detailed steps"
echo ""

echo "🤖 Step 6: Get Claude API Key"
echo "-------------------------------"
echo "# 1. Sign up at Anthropic Console"
echo "open https://console.anthropic.com"
echo ""
echo "# 2. Create API key"
echo "# 3. Add to android/local.properties:"
echo "#   CLAUDE_API_KEY=sk-ant-api03-..."
echo ""

echo "✅ Step 7: Build the App"
echo "-------------------------"
echo "cd /Users/I808883/app/claude/android"
echo "./gradlew clean build"
echo ""

echo "📱 Step 8: Install on Device"
echo "------------------------------"
echo "# Connect Android device via USB"
echo "# Enable Developer Options and USB Debugging on device"
echo ""
echo "adb devices  # Verify device connected"
echo "./gradlew installDebug"
echo ""

echo "🚀 Step 9: Launch and Test"
echo "----------------------------"
echo "adb shell am start -n com.skylens/.MainActivity"
echo "adb logcat -s SkyLens:*  # View logs"
echo ""

echo "================================="
echo "Need help? Check the documentation:"
echo "  - docs/JAVA_SETUP.md"
echo "  - docs/API_INTEGRATION.md"
echo "  - docs/BUILD_GUIDE.md"
echo "  - PROJECT_STATUS.md"
echo ""
echo "Or run: ./scripts/verify_environment.sh"
